# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/CYC

    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.4.1-node-browsers
      - image: circleci/postgres:9.5-alpine

        steps:
      - checkout
      - run: bundle install --path vendor/bundle
      - run: bundle exec rake db:drop
      - run: bundle exec rake db:create RAILS_ENV=test
      - run: bundle exec rake db:migrate RAILS_ENV=test
      - run: bundle exec rake test
      - run: bundle exec rspec spec
        